sonar.projectKey=DEFRA_lis-taxonomy-register
sonar.organization=defra
sonar.qualitygate.ignoreSmallChanges=false

sonar.links.homepage=https://github.com/DEFRA/lis-taxonomy-register
sonar.links.ci=https://github.com/DEFRA/lis-taxonomy-register/actions
sonar.links.scm=https://github.com/DEFRA/lis-taxonomy-register
sonar.links.issue=https://github.com/DEFRA/lis-taxonomy-register/issues

sonar.sources=src
sonar.tests=src,test

sonar.exclusions=\
  src/**/*.test.js,\
  src/**/*.spec.js,\
  src/**/*.test.ts,\
  src/**/*.spec.ts,\
  src/**/*.test.jsx,\
  src/**/*.spec.jsx,\
  src/**/*.test.tsx,\
  src/**/*.spec.tsx

sonar.test.inclusions=\
  src/**/*.test.js,\
  src/**/*.spec.js,\
  src/**/*.test.ts,\
  src/**/*.spec.ts,\
  src/**/*.test.jsx,\
  src/**/*.spec.jsx,\
  src/**/*.test.tsx,\
  src/**/*.spec.tsx,\
  test/**/*.test.js,\
  test/**/*.spec.js,\
  test/**/*.test.ts,\
  test/**/*.spec.ts,\
  test/**/*.test.jsx,\
  test/**/*.spec.jsx,\
  test/**/*.test.tsx,\
  test/**/*.spec.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
